---
dist: bionic
language: minimal

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

jobs:
  include:

    - stage: test
      install:
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
        - sudo dpkg -i vagrant_2.2.9_x86_64.deb
        - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload
      script:
        - openssl genrsa -out salt/keys/openvpn-saltmaster.pem
        - openssl rsa -in salt/keys/openvpn-saltmaster.pem -pubout -out salt/keys/openvpn-saltmaster.pub
        - openssl genrsa -out salt/keys/openvpn-server-box.pem
        - openssl rsa -in salt/keys/openvpn-server-box.pem -pubout -out salt/keys/openvpn-server-box.pub
        - openssl genrsa -out salt/keys/openvpn-client-box.pem
        - openssl rsa -in salt/keys/openvpn-client-box.pem -pubout -out salt/keys/openvpn-client-box.pub
        - sudo vagrant up --provider=libvirt openvpn-saltmaster
        - sudo vagrant halt openvpn-saltmaster
        - sudo vagrant up --provider=libvirt openvpn-server-box
        - sudo vagrant halt openvpn-server-box
        - sudo vagrant up --provider=libvirt openvpn-client-box
        - sudo vagrant halt openvpn-client-box
        - sudo vagrant up --provider=libvirt openvpn-saltmaster
        - sudo vagrant up --provider=libvirt openvpn-server-box
        - sudo vagrant up --provider=libvirt openvpn-client-box
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' state.highstate saltenv=base
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-client-box' state.highstate saltenv=base
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' state.sls openvpn.easyrsa
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' state.sls openvpn.configure-server
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' service.start openvpn@server
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' service.enable openvpn@server
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-server-box' state.sls openvpn.clientkey pillar=\'{"hostname":\ "openvpn-client-box"}\'
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt-cp --chunked 'openvpn-client-box' /var/cache/salt/master/minions/openvpn-server-box/files/etc/openvpn/client/ etc/openvpn/
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-client-box' state.sls openvpn.configure-client pillar=\'{"hostname":\ "openvpn-client-box"}\'
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-client-box' service.start openvpn@client
        - sudo vagrant ssh openvpn-saltmaster -- sudo salt 'openvpn-client-box' service.enable openvpn@client
        - sudo vagrant ssh openvpn-client-box -- ping 10.8.0.1 -c 10
        - sudo vagrant destroy --force

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: QmCdUbd7k3gWm62hWHvhWSsAaTjEcaUKQEIqkt4Wcmt2i86M4o0zAwfQUdDvK+RY9vl8AiKjL7CBvA0MfEEB4QAZBwLcpZiEE3PAg1K+Fe1UQZK4ZKbeVc1vp5p7M1df68cY+7n1D6joImAOyPxq9MMANYL0sYLd4Zjzl4KM1xvwekjXufco9xgCSdszzo/tBUA0C50JgyL58CZFxS3qR2/qweYnbPqnjR1c3SCu2V58pTs+UQulGpmPbmg2emhjOUIyljBMG85Xiw9ZRscrVD46BnBLIlJnr+4jnqCJmlV+Cq2esK6mYZwUIfnqueiaC6FrSI9ym90jd1taCW0RXkMF+Eq4XKz2WJSuss2kl7T9UGxPoBlnXbONRrNcv4YLHxrQrOUqEvVEJpPR9HtEFK3NkPP56HJtwvyqpjuk0reN2NI9SfYshZvjLASag6GkysReHQzhGJ6SvqHE3+0hMyZ+5o2spsXwlnWff0U77gDTW+1LFrPyn1mGLHcXMSKDVX97AndhOdaS9f2dRnDrCPXS+2gzs8fjJhcDY3nXXKKaHKjYrYVFPfDZL4kNmuFPvRvTDAG+zD2cMns9AVZ8RpEsyQpgsBQWon26JFKlVMz3FphblCL0aDu8z2JOO8/NUP3h1zMgomX2NddzXxPGw24jshq63wUsc9xE3O8mDQo=
